name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./5_Testing/tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Tests
        run: npm test

  e2e-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./5_Testing/tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Tests e2e
        run: npm run test:e2e:ci
      - name: Upload screenshots when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./cypress/screenshots
      - name: Upload videos when specs fail
        if: ${{ failure()}}
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: ./cypress/videos
